name: core
description: Some service description
expose: env
run: npm start
options:
    - name: redis
      description: Path to redis database
      value: GATEHUB_REDIS
      lables:
          global: true
